id: I6CC9D5D5
legacy_id: P001711
ocr_import_info:
  bdrc_scan_id: W00KG04005
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:34:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:19:15.064063+00:00'
last_modified: 2022-08-29 20:19:33.838290
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG04005
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG04005
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་གཤེགས་བདུན་གྱི་མཆོད་པའི་ཆོག་བསྒྲིགས་ཡིད་བཞིན་དབང་རྒྱལ།
  author: ཏཱ་ལའི་བླ་མ ༠༥་ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7857321613762559
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I00KG06678:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG06678
      total_pages: 208
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG06678.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.7857321613762559
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
