id: P001711
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:16:03.416149
source_metadata:
  id: bdr:W00KG04005
  title: བདེ་གཤེགས་བདུན་གྱི་མཆོད་པའི་ཆོག་བསྒྲིགས་ཡིད་བཞིན་དབང་རྒྱལ།
  author: ''
  volumes:
    535ee9fbfc524f9099baf3c145dda6d2:
      image_group_id: I00KG06678
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
